### ISSUE TITLE
Streaming on the current request/request

### ISSUE THREAD

**Issue by angadn** [suprememoocow/request-extensible#1]
I seem to get this error while `return request(url)`.

```
TypeError: current is not a function
<br> &nbsp; &nbsp;at next (/node_modules/request-extensible/lib/request-extensible.js:16:14)
```

Here is how I'm setup:

```
request = requestExt({
      request: require("request"),
      extensions: [
        new RequestHttpCache({
          backend: "redis",
          redisClient: redisProvider.client()
        })
      ]
    });
```

**Comment by suprememoocow** [comment]
Hi,

Try the following:

```
request = requestExt({
      request: require("request"),
      extensions: [
        new RequestHttpCache({
          backend: "redis",
          redisClient: redisProvider.client()
        }).extension
      ]
    });
```

(Note the `.extension` at the end of the `RequestHttpCache` constructor)

**Comment by angadn** [comment]
Definitely seems to head in the right direction: My error has now changed to this:

```
usr/src/my-project/node_modules/request-http-cache/lib/index.js:243
      callback(null, response, body);
      ^

TypeError: callback is not a function
    at Request._callback (/usr/src/my-project/node_modules/request-http-cache/lib/index.js:243:7)
    at Request.self.callback (/usr/src/my-project/node_modules/request/request.js:199:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/src/my-project/node_modules/request/request.js:1036:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/src/my-project/node_modules/request/request.js:963:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)

```

On adding a `function(err, res, body) { }` style parameter, obviously `request` returns undefined instead of a stream.

Edit: Creating another issue for your convenience in case it is more relevant to the other repository: https://github.com/gitterHQ/request-http-cache/issues/5
